// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// CTRL
// 0x0000 : Control signals
//          bit 0  - ap_start (Read/Write/COH)
//          bit 1  - ap_done (Read/COR)
//          bit 2  - ap_idle (Read)
//          bit 3  - ap_ready (Read)
//          bit 7  - auto_restart (Read/Write)
//          others - reserved
// 0x0004 : Global Interrupt Enable Register
//          bit 0  - Global Interrupt Enable (Read/Write)
//          others - reserved
// 0x0008 : IP Interrupt Enable Register (Read/Write)
//          bit 0  - Channel 0 (ap_done)
//          bit 1  - Channel 1 (ap_ready)
//          others - reserved
// 0x000c : IP Interrupt Status Register (Read/TOW)
//          bit 0  - Channel 0 (ap_done)
//          bit 1  - Channel 1 (ap_ready)
//          others - reserved
// 0x2000 ~
// 0x3fff : Memory 'pmod_data' (4096 * 16b)
//          Word n : bit [15: 0] - pmod_data[2n]
//                   bit [31:16] - pmod_data[2n+1]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XPOSITIONCTRL_CTRL_ADDR_AP_CTRL        0x0000
#define XPOSITIONCTRL_CTRL_ADDR_GIE            0x0004
#define XPOSITIONCTRL_CTRL_ADDR_IER            0x0008
#define XPOSITIONCTRL_CTRL_ADDR_ISR            0x000c
#define XPOSITIONCTRL_CTRL_ADDR_PMOD_DATA_BASE 0x2000
#define XPOSITIONCTRL_CTRL_ADDR_PMOD_DATA_HIGH 0x3fff
#define XPOSITIONCTRL_CTRL_WIDTH_PMOD_DATA     16
#define XPOSITIONCTRL_CTRL_DEPTH_PMOD_DATA     4096

