// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// CTRL
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/SC)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        others - reserved
// 0x28 : Data signal of obj_avd_cmd
//        bit 15~0 - obj_avd_cmd[15:0] (Read/Write)
//        others   - reserved
// 0x2c : reserved
// 0x30 : Data signal of obj_avd_flag
//        bit 15~0 - obj_avd_flag[15:0] (Read/Write)
//        others   - reserved
// 0x34 : reserved
// 0x10 ~
// 0x1f : Memory 'rcCmdIn' (5 * 16b)
//        Word n : bit [15: 0] - rcCmdIn[2n]
//                 bit [31:16] - rcCmdIn[2n+1]
// 0x20 ~
// 0x27 : Memory 'measured' (4 * 16b)
//        Word n : bit [15: 0] - measured[2n]
//                 bit [31:16] - measured[2n+1]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XFLIGHTMAIN_CTRL_ADDR_AP_CTRL           0x00
#define XFLIGHTMAIN_CTRL_ADDR_GIE               0x04
#define XFLIGHTMAIN_CTRL_ADDR_IER               0x08
#define XFLIGHTMAIN_CTRL_ADDR_ISR               0x0c
#define XFLIGHTMAIN_CTRL_ADDR_OBJ_AVD_CMD_DATA  0x28
#define XFLIGHTMAIN_CTRL_BITS_OBJ_AVD_CMD_DATA  16
#define XFLIGHTMAIN_CTRL_ADDR_OBJ_AVD_FLAG_DATA 0x30
#define XFLIGHTMAIN_CTRL_BITS_OBJ_AVD_FLAG_DATA 16
#define XFLIGHTMAIN_CTRL_ADDR_RCCMDIN_BASE      0x10
#define XFLIGHTMAIN_CTRL_ADDR_RCCMDIN_HIGH      0x1f
#define XFLIGHTMAIN_CTRL_WIDTH_RCCMDIN          16
#define XFLIGHTMAIN_CTRL_DEPTH_RCCMDIN          5
#define XFLIGHTMAIN_CTRL_ADDR_MEASURED_BASE     0x20
#define XFLIGHTMAIN_CTRL_ADDR_MEASURED_HIGH     0x27
#define XFLIGHTMAIN_CTRL_WIDTH_MEASURED         16
#define XFLIGHTMAIN_CTRL_DEPTH_MEASURED         4

