// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// ctrl
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of min_duty
//        bit 15~0 - min_duty[15:0] (Read/Write)
//        others   - reserved
// 0x14 : reserved
// 0x18 : Data signal of max_duty
//        bit 15~0 - max_duty[15:0] (Read/Write)
//        others   - reserved
// 0x1c : reserved
// 0x20 : Data signal of period
//        bit 15~0 - period[15:0] (Read/Write)
//        others   - reserved
// 0x24 : reserved
// 0x30 ~
// 0x3f : Memory 'm_V' (6 * 16b)
//        Word n : bit [15: 0] - m_V[2n]
//                 bit [31:16] - m_V[2n+1]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XPWM_CTRL_ADDR_AP_CTRL       0x00
#define XPWM_CTRL_ADDR_GIE           0x04
#define XPWM_CTRL_ADDR_IER           0x08
#define XPWM_CTRL_ADDR_ISR           0x0c
#define XPWM_CTRL_ADDR_MIN_DUTY_DATA 0x10
#define XPWM_CTRL_BITS_MIN_DUTY_DATA 16
#define XPWM_CTRL_ADDR_MAX_DUTY_DATA 0x18
#define XPWM_CTRL_BITS_MAX_DUTY_DATA 16
#define XPWM_CTRL_ADDR_PERIOD_DATA   0x20
#define XPWM_CTRL_BITS_PERIOD_DATA   16
#define XPWM_CTRL_ADDR_M_V_BASE      0x30
#define XPWM_CTRL_ADDR_M_V_HIGH      0x3f
#define XPWM_CTRL_WIDTH_M_V          16
#define XPWM_CTRL_DEPTH_M_V          6

