// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xpwm.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XPwm_CfgInitialize(XPwm *InstancePtr, XPwm_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Ctrl_BaseAddress = ConfigPtr->Ctrl_BaseAddress;
    InstancePtr->Test_BaseAddress = ConfigPtr->Test_BaseAddress;
    InstancePtr->Test2_BaseAddress = ConfigPtr->Test2_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XPwm_Start(XPwm *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPwm_ReadReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_ADDR_AP_CTRL) & 0x80;
    XPwm_WriteReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_ADDR_AP_CTRL, Data | 0x01);
}

u32 XPwm_IsDone(XPwm *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPwm_ReadReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XPwm_IsIdle(XPwm *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPwm_ReadReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XPwm_IsReady(XPwm *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPwm_ReadReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XPwm_EnableAutoRestart(XPwm *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPwm_WriteReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_ADDR_AP_CTRL, 0x80);
}

void XPwm_DisableAutoRestart(XPwm *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPwm_WriteReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_ADDR_AP_CTRL, 0);
}

void XPwm_Set_min_duty(XPwm *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPwm_WriteReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_ADDR_MIN_DUTY_DATA, Data);
}

u32 XPwm_Get_min_duty(XPwm *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPwm_ReadReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_ADDR_MIN_DUTY_DATA);
    return Data;
}

void XPwm_Set_max_duty(XPwm *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPwm_WriteReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_ADDR_MAX_DUTY_DATA, Data);
}

u32 XPwm_Get_max_duty(XPwm *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPwm_ReadReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_ADDR_MAX_DUTY_DATA);
    return Data;
}

void XPwm_Set_period(XPwm *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPwm_WriteReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_ADDR_PERIOD_DATA, Data);
}

u32 XPwm_Get_period(XPwm *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPwm_ReadReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_ADDR_PERIOD_DATA);
    return Data;
}

u32 XPwm_Get_motorCmd_V_BaseAddress(XPwm *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XPWM_CTRL_ADDR_MOTORCMD_V_BASE);
}

u32 XPwm_Get_motorCmd_V_HighAddress(XPwm *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XPWM_CTRL_ADDR_MOTORCMD_V_HIGH);
}

u32 XPwm_Get_motorCmd_V_TotalBytes(XPwm *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XPWM_CTRL_ADDR_MOTORCMD_V_HIGH - XPWM_CTRL_ADDR_MOTORCMD_V_BASE + 1);
}

u32 XPwm_Get_motorCmd_V_BitWidth(XPwm *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XPWM_CTRL_WIDTH_MOTORCMD_V;
}

u32 XPwm_Get_motorCmd_V_Depth(XPwm *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XPWM_CTRL_DEPTH_MOTORCMD_V;
}

u32 XPwm_Write_motorCmd_V_Words(XPwm *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XPWM_CTRL_ADDR_MOTORCMD_V_HIGH - XPWM_CTRL_ADDR_MOTORCMD_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Ctrl_BaseAddress + XPWM_CTRL_ADDR_MOTORCMD_V_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XPwm_Read_motorCmd_V_Words(XPwm *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XPWM_CTRL_ADDR_MOTORCMD_V_HIGH - XPWM_CTRL_ADDR_MOTORCMD_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Ctrl_BaseAddress + XPWM_CTRL_ADDR_MOTORCMD_V_BASE + (offset + i)*4);
    }
    return length;
}

u32 XPwm_Write_motorCmd_V_Bytes(XPwm *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XPWM_CTRL_ADDR_MOTORCMD_V_HIGH - XPWM_CTRL_ADDR_MOTORCMD_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Ctrl_BaseAddress + XPWM_CTRL_ADDR_MOTORCMD_V_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XPwm_Read_motorCmd_V_Bytes(XPwm *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XPWM_CTRL_ADDR_MOTORCMD_V_HIGH - XPWM_CTRL_ADDR_MOTORCMD_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Ctrl_BaseAddress + XPWM_CTRL_ADDR_MOTORCMD_V_BASE + offset + i);
    }
    return length;
}

u32 XPwm_Get_test_BaseAddress(XPwm *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Test_BaseAddress + XPWM_TEST_ADDR_TEST_BASE);
}

u32 XPwm_Get_test_HighAddress(XPwm *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Test_BaseAddress + XPWM_TEST_ADDR_TEST_HIGH);
}

u32 XPwm_Get_test_TotalBytes(XPwm *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XPWM_TEST_ADDR_TEST_HIGH - XPWM_TEST_ADDR_TEST_BASE + 1);
}

u32 XPwm_Get_test_BitWidth(XPwm *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XPWM_TEST_WIDTH_TEST;
}

u32 XPwm_Get_test_Depth(XPwm *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XPWM_TEST_DEPTH_TEST;
}

u32 XPwm_Write_test_Words(XPwm *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XPWM_TEST_ADDR_TEST_HIGH - XPWM_TEST_ADDR_TEST_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Test_BaseAddress + XPWM_TEST_ADDR_TEST_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XPwm_Read_test_Words(XPwm *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XPWM_TEST_ADDR_TEST_HIGH - XPWM_TEST_ADDR_TEST_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Test_BaseAddress + XPWM_TEST_ADDR_TEST_BASE + (offset + i)*4);
    }
    return length;
}

u32 XPwm_Write_test_Bytes(XPwm *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XPWM_TEST_ADDR_TEST_HIGH - XPWM_TEST_ADDR_TEST_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Test_BaseAddress + XPWM_TEST_ADDR_TEST_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XPwm_Read_test_Bytes(XPwm *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XPWM_TEST_ADDR_TEST_HIGH - XPWM_TEST_ADDR_TEST_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Test_BaseAddress + XPWM_TEST_ADDR_TEST_BASE + offset + i);
    }
    return length;
}

u32 XPwm_Get_test2_V_BaseAddress(XPwm *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Test2_BaseAddress + XPWM_TEST2_ADDR_TEST2_V_BASE);
}

u32 XPwm_Get_test2_V_HighAddress(XPwm *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Test2_BaseAddress + XPWM_TEST2_ADDR_TEST2_V_HIGH);
}

u32 XPwm_Get_test2_V_TotalBytes(XPwm *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XPWM_TEST2_ADDR_TEST2_V_HIGH - XPWM_TEST2_ADDR_TEST2_V_BASE + 1);
}

u32 XPwm_Get_test2_V_BitWidth(XPwm *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XPWM_TEST2_WIDTH_TEST2_V;
}

u32 XPwm_Get_test2_V_Depth(XPwm *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XPWM_TEST2_DEPTH_TEST2_V;
}

u32 XPwm_Write_test2_V_Words(XPwm *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XPWM_TEST2_ADDR_TEST2_V_HIGH - XPWM_TEST2_ADDR_TEST2_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Test2_BaseAddress + XPWM_TEST2_ADDR_TEST2_V_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XPwm_Read_test2_V_Words(XPwm *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XPWM_TEST2_ADDR_TEST2_V_HIGH - XPWM_TEST2_ADDR_TEST2_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Test2_BaseAddress + XPWM_TEST2_ADDR_TEST2_V_BASE + (offset + i)*4);
    }
    return length;
}

u32 XPwm_Write_test2_V_Bytes(XPwm *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XPWM_TEST2_ADDR_TEST2_V_HIGH - XPWM_TEST2_ADDR_TEST2_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Test2_BaseAddress + XPWM_TEST2_ADDR_TEST2_V_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XPwm_Read_test2_V_Bytes(XPwm *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XPWM_TEST2_ADDR_TEST2_V_HIGH - XPWM_TEST2_ADDR_TEST2_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Test2_BaseAddress + XPWM_TEST2_ADDR_TEST2_V_BASE + offset + i);
    }
    return length;
}

void XPwm_InterruptGlobalEnable(XPwm *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPwm_WriteReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_ADDR_GIE, 1);
}

void XPwm_InterruptGlobalDisable(XPwm *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPwm_WriteReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_ADDR_GIE, 0);
}

void XPwm_InterruptEnable(XPwm *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XPwm_ReadReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_ADDR_IER);
    XPwm_WriteReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_ADDR_IER, Register | Mask);
}

void XPwm_InterruptDisable(XPwm *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XPwm_ReadReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_ADDR_IER);
    XPwm_WriteReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_ADDR_IER, Register & (~Mask));
}

void XPwm_InterruptClear(XPwm *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPwm_WriteReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_ADDR_ISR, Mask);
}

u32 XPwm_InterruptGetEnabled(XPwm *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XPwm_ReadReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_ADDR_IER);
}

u32 XPwm_InterruptGetStatus(XPwm *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XPwm_ReadReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_ADDR_ISR);
}

