// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xaxi_uart_driver.h"

extern XAxi_uart_driver_Config XAxi_uart_driver_ConfigTable[];

XAxi_uart_driver_Config *XAxi_uart_driver_LookupConfig(u16 DeviceId) {
	XAxi_uart_driver_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XAXI_UART_DRIVER_NUM_INSTANCES; Index++) {
		if (XAxi_uart_driver_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XAxi_uart_driver_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XAxi_uart_driver_Initialize(XAxi_uart_driver *InstancePtr, u16 DeviceId) {
	XAxi_uart_driver_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XAxi_uart_driver_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XAxi_uart_driver_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

