// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xaxi_spi_driver.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XAxi_spi_driver_CfgInitialize(XAxi_spi_driver *InstancePtr, XAxi_spi_driver_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Debug_BaseAddress = ConfigPtr->Debug_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XAxi_spi_driver_Set_TX_message_V(XAxi_spi_driver *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAxi_spi_driver_WriteReg(InstancePtr->Debug_BaseAddress, XAXI_SPI_DRIVER_DEBUG_ADDR_TX_MESSAGE_V_DATA, Data);
}

u32 XAxi_spi_driver_Get_TX_message_V(XAxi_spi_driver *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAxi_spi_driver_ReadReg(InstancePtr->Debug_BaseAddress, XAXI_SPI_DRIVER_DEBUG_ADDR_TX_MESSAGE_V_DATA);
    return Data;
}

u32 XAxi_spi_driver_Get_RX_message_V(XAxi_spi_driver *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAxi_spi_driver_ReadReg(InstancePtr->Debug_BaseAddress, XAXI_SPI_DRIVER_DEBUG_ADDR_RX_MESSAGE_V_DATA);
    return Data;
}

u32 XAxi_spi_driver_Get_RX_message_V_vld(XAxi_spi_driver *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAxi_spi_driver_ReadReg(InstancePtr->Debug_BaseAddress, XAXI_SPI_DRIVER_DEBUG_ADDR_RX_MESSAGE_V_CTRL);
    return Data & 0x1;
}

